### ISSUE TITLE
Different ENV for different platforms

### ISSUE THREAD

**Issue by ArionThinker** [ArionThinker/tea-package-builder#9]
```
env:
    ARGS:
        - --prefix={{prefix}}
    darwin:
        ARGS:
            - --without-foo
````
